In [1]:
import numpy as np

Assignment:
Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The return object should appear as:
{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}

In [9]:
# Create list
digits = np.arange(9)
print(digits)

In [10]:
# Convert to matrix array
matrix = digits.reshape(3, 3)
print(

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
# Get mean by row
matrix.mean(axis=0).tolist()

[3.0, 4.0, 5.0]

In [23]:
# Get mean by column
matrix.mean(axis=1).tolist()

[1.0, 4.0, 7.0]

In [24]:
# Get flattened mean
matrix.mean()

4.0

In [43]:
# Combined functions
[matrix.mean(axis=0).tolist(), matrix.mean(axis=1).tolist(), matrix.mean()]

[[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]

In [27]:
# Get variance by row
matrix.var(axis=0).tolist()

[6.0, 6.0, 6.0]

In [28]:
# Get variance by column
matrix.var(axis=1).tolist()

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [29]:
# Get flattened variance
matrix.var()

6.666666666666667

In [30]:
# Get standard deviation by row
matrix.std(axis=0).tolist()

[2.449489742783178, 2.449489742783178, 2.449489742783178]

In [31]:
# Get standard deviation by column
matrix.std(axis=1).tolist()

[0.816496580927726, 0.816496580927726, 0.816496580927726]

In [32]:
# Get flattened standard deviation
matrix.std()

2.581988897471611

In [35]:
# Get max by row
matrix.max(axis=0).tolist()

[6, 7, 8]

In [36]:
# Get max by column
matrix.max(axis=1).tolist()

[2, 5, 8]

In [37]:
# Get flattened max
matrix.max()

8

In [38]:
# Get min by row
matrix.min(axis=0).tolist()

[0, 1, 2]

In [41]:
# Get min by column
matrix.min(axis=1).tolist()

[0, 3, 6]

In [42]:
# Get flattened min
matrix.min()

0